syntax = "proto3";

package pb;

option go_package = "github.com/koliader/tellmi-sdk/proto/pb";

message User {
  string id = 1;
  string username = 2;
  string role = 3;
  bool isBlocked = 4;
}

message Post {
  int64 id = 1;
  string title = 2;
  string description = 3;
  string userId = 4;
  int64 categoryId = 5;
}

message PostRow {
  int64 id = 1;
  string title = 2;
  string description = 3;
  User user = 4;
  Category category = 5;
}

message Comment {
  int64 id = 1;
  string comment = 2;
  int64 postId = 3;
  string userId = 4;
}

message CommentRow {
  int64 id = 1;
  string comment = 2;
  int64 postId = 3;
  User user = 4;
  PostRow post = 5;
}

message Category {
  int64 id = 1;
  string name = 2;
}

message Empty {}

message Success {
  string message = 1;
}

message PaginationReq {
  int32 limit = 1;
  int32 offset = 2;
}
