// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: Posts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostReq) Reset() {
	*x = CreatePostReq{}
	mi := &file_Posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostReq) ProtoMessage() {}

func (x *CreatePostReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostReq.ProtoReflect.Descriptor instead.
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePostReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type ListPostsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostRow             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPostsRes) Reset() {
	*x = ListPostsRes{}
	mi := &file_Posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPostsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPostsRes) ProtoMessage() {}

func (x *ListPostsRes) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPostsRes.ProtoReflect.Descriptor instead.
func (*ListPostsRes) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{1}
}

func (x *ListPostsRes) GetPosts() []*PostRow {
	if x != nil {
		return x.Posts
	}
	return nil
}

type GetByIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDReq) Reset() {
	*x = GetByIDReq{}
	mi := &file_Posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDReq) ProtoMessage() {}

func (x *GetByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDReq.ProtoReflect.Descriptor instead.
func (*GetByIDReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{2}
}

func (x *GetByIDReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditPostReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPostReq) Reset() {
	*x = EditPostReq{}
	mi := &file_Posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPostReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPostReq) ProtoMessage() {}

func (x *EditPostReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPostReq.ProtoReflect.Descriptor instead.
func (*EditPostReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{3}
}

func (x *EditPostReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditPostReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EditPostReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EditPostReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type ListCategoriesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRes) Reset() {
	*x = ListCategoriesRes{}
	mi := &file_Posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRes) ProtoMessage() {}

func (x *ListCategoriesRes) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRes.ProtoReflect.Descriptor instead.
func (*ListCategoriesRes) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesRes) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryReq) Reset() {
	*x = CreateCategoryReq{}
	mi := &file_Posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryReq) ProtoMessage() {}

func (x *CreateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryReq.ProtoReflect.Descriptor instead.
func (*CreateCategoryReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCategoryReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EditCategoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCategoryReq) Reset() {
	*x = EditCategoryReq{}
	mi := &file_Posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCategoryReq) ProtoMessage() {}

func (x *EditCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCategoryReq.ProtoReflect.Descriptor instead.
func (*EditCategoryReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{6}
}

func (x *EditCategoryReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditCategoryReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       string                 `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	PostId        int64                  `protobuf:"varint,2,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_Posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCommentReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateCommentReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type EditCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCommentReq) Reset() {
	*x = EditCommentReq{}
	mi := &file_Posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCommentReq) ProtoMessage() {}

func (x *EditCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCommentReq.ProtoReflect.Descriptor instead.
func (*EditCommentReq) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{8}
}

func (x *EditCommentReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditCommentReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ListCommentsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentRow          `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRes) Reset() {
	*x = ListCommentsRes{}
	mi := &file_Posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRes) ProtoMessage() {}

func (x *ListCommentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_Posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRes.ProtoReflect.Descriptor instead.
func (*ListCommentsRes) Descriptor() ([]byte, []int) {
	return file_Posts_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommentsRes) GetComments() []*CommentRow {
	if x != nil {
		return x.Comments
	}
	return nil
}

var File_Posts_proto protoreflect.FileDescriptor

const file_Posts_proto_rawDesc = "" +
	"\n" +
	"\vPosts.proto\x12\x02pb\x1a\fEntity.proto\"g\n" +
	"\rCreatePostReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x03 \x01(\x03R\n" +
	"categoryId\"1\n" +
	"\fListPostsRes\x12!\n" +
	"\x05posts\x18\x01 \x03(\v2\v.pb.PostRowR\x05posts\"\x1c\n" +
	"\n" +
	"GetByIDReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"u\n" +
	"\vEditPostReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x04 \x01(\x03R\n" +
	"categoryId\"A\n" +
	"\x11ListCategoriesRes\x12,\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\f.pb.CategoryR\n" +
	"categories\"'\n" +
	"\x11CreateCategoryReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x0fEditCategoryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"D\n" +
	"\x10CreateCommentReq\x12\x18\n" +
	"\acomment\x18\x01 \x01(\tR\acomment\x12\x16\n" +
	"\x06postId\x18\x02 \x01(\x03R\x06postId\":\n" +
	"\x0eEditCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"=\n" +
	"\x0fListCommentsRes\x12*\n" +
	"\bcomments\x18\x01 \x03(\v2\x0e.pb.CommentRowR\bcomments2\xdc\x04\n" +
	"\x05Posts\x12+\n" +
	"\n" +
	"CreatePost\x12\x11.pb.CreatePostReq\x1a\b.pb.Post\"\x00\x12*\n" +
	"\tListPosts\x12\t.pb.Empty\x1a\x10.pb.ListPostsRes\"\x00\x12,\n" +
	"\vGetPostByID\x12\x0e.pb.GetByIDReq\x1a\v.pb.PostRow\"\x00\x12'\n" +
	"\bEditPost\x12\x0f.pb.EditPostReq\x1a\b.pb.Post\"\x00\x12+\n" +
	"\n" +
	"DeletePost\x12\x0e.pb.GetByIDReq\x1a\v.pb.Success\"\x00\x127\n" +
	"\x0eCreateCategory\x12\x15.pb.CreateCategoryReq\x1a\f.pb.Category\"\x00\x124\n" +
	"\x0eListCategories\x12\t.pb.Empty\x1a\x15.pb.ListCategoriesRes\"\x00\x122\n" +
	"\fEditCategory\x12\x13.pb.EditCategoryReq\x1a\v.pb.Success\"\x00\x124\n" +
	"\rCreateComment\x12\x14.pb.CreateCommentReq\x1a\v.pb.Comment\"\x00\x12;\n" +
	"\x12ListCommentsByPost\x12\x0e.pb.GetByIDReq\x1a\x13.pb.ListCommentsRes\"\x00\x120\n" +
	"\vEditComment\x12\x12.pb.EditCommentReq\x1a\v.pb.Comment\"\x00\x12.\n" +
	"\rDeleteComment\x12\x0e.pb.GetByIDReq\x1a\v.pb.Success\"\x00B)Z'github.com/koliader/tellmi-sdk/proto/pbb\x06proto3"

var (
	file_Posts_proto_rawDescOnce sync.Once
	file_Posts_proto_rawDescData []byte
)

func file_Posts_proto_rawDescGZIP() []byte {
	file_Posts_proto_rawDescOnce.Do(func() {
		file_Posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Posts_proto_rawDesc), len(file_Posts_proto_rawDesc)))
	})
	return file_Posts_proto_rawDescData
}

var file_Posts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Posts_proto_goTypes = []any{
	(*CreatePostReq)(nil),     // 0: pb.CreatePostReq
	(*ListPostsRes)(nil),      // 1: pb.ListPostsRes
	(*GetByIDReq)(nil),        // 2: pb.GetByIDReq
	(*EditPostReq)(nil),       // 3: pb.EditPostReq
	(*ListCategoriesRes)(nil), // 4: pb.ListCategoriesRes
	(*CreateCategoryReq)(nil), // 5: pb.CreateCategoryReq
	(*EditCategoryReq)(nil),   // 6: pb.EditCategoryReq
	(*CreateCommentReq)(nil),  // 7: pb.CreateCommentReq
	(*EditCommentReq)(nil),    // 8: pb.EditCommentReq
	(*ListCommentsRes)(nil),   // 9: pb.ListCommentsRes
	(*PostRow)(nil),           // 10: pb.PostRow
	(*Category)(nil),          // 11: pb.Category
	(*CommentRow)(nil),        // 12: pb.CommentRow
	(*Empty)(nil),             // 13: pb.Empty
	(*Post)(nil),              // 14: pb.Post
	(*Success)(nil),           // 15: pb.Success
	(*Comment)(nil),           // 16: pb.Comment
}
var file_Posts_proto_depIdxs = []int32{
	10, // 0: pb.ListPostsRes.posts:type_name -> pb.PostRow
	11, // 1: pb.ListCategoriesRes.categories:type_name -> pb.Category
	12, // 2: pb.ListCommentsRes.comments:type_name -> pb.CommentRow
	0,  // 3: pb.Posts.CreatePost:input_type -> pb.CreatePostReq
	13, // 4: pb.Posts.ListPosts:input_type -> pb.Empty
	2,  // 5: pb.Posts.GetPostByID:input_type -> pb.GetByIDReq
	3,  // 6: pb.Posts.EditPost:input_type -> pb.EditPostReq
	2,  // 7: pb.Posts.DeletePost:input_type -> pb.GetByIDReq
	5,  // 8: pb.Posts.CreateCategory:input_type -> pb.CreateCategoryReq
	13, // 9: pb.Posts.ListCategories:input_type -> pb.Empty
	6,  // 10: pb.Posts.EditCategory:input_type -> pb.EditCategoryReq
	7,  // 11: pb.Posts.CreateComment:input_type -> pb.CreateCommentReq
	2,  // 12: pb.Posts.ListCommentsByPost:input_type -> pb.GetByIDReq
	8,  // 13: pb.Posts.EditComment:input_type -> pb.EditCommentReq
	2,  // 14: pb.Posts.DeleteComment:input_type -> pb.GetByIDReq
	14, // 15: pb.Posts.CreatePost:output_type -> pb.Post
	1,  // 16: pb.Posts.ListPosts:output_type -> pb.ListPostsRes
	10, // 17: pb.Posts.GetPostByID:output_type -> pb.PostRow
	14, // 18: pb.Posts.EditPost:output_type -> pb.Post
	15, // 19: pb.Posts.DeletePost:output_type -> pb.Success
	11, // 20: pb.Posts.CreateCategory:output_type -> pb.Category
	4,  // 21: pb.Posts.ListCategories:output_type -> pb.ListCategoriesRes
	15, // 22: pb.Posts.EditCategory:output_type -> pb.Success
	16, // 23: pb.Posts.CreateComment:output_type -> pb.Comment
	9,  // 24: pb.Posts.ListCommentsByPost:output_type -> pb.ListCommentsRes
	16, // 25: pb.Posts.EditComment:output_type -> pb.Comment
	15, // 26: pb.Posts.DeleteComment:output_type -> pb.Success
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_Posts_proto_init() }
func file_Posts_proto_init() {
	if File_Posts_proto != nil {
		return
	}
	file_Entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Posts_proto_rawDesc), len(file_Posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Posts_proto_goTypes,
		DependencyIndexes: file_Posts_proto_depIdxs,
		MessageInfos:      file_Posts_proto_msgTypes,
	}.Build()
	File_Posts_proto = out.File
	file_Posts_proto_goTypes = nil
	file_Posts_proto_depIdxs = nil
}
